// <auto-generated/>
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Axity.Commons.Extensions;
global using Axity.Users.Common;
global using Axity.Users.Common.DTOs.Requests.Users;
global using Axity.Users.Common.DTOs.Responses.Users;
global using Axity.Users.Model.Entities;
global using Axity.Users.Persistence.DAO.Users;
global using Axity.Users.Services.Mapping;
global using Axity.Users.Services.Users;
global using Axity.Users.Services.Users.Impl;
global using Microsoft.Extensions.DependencyInjection;