// <auto-generated/>
global using Axity.Users.Model.Entities;
global using Axity.Users.Persistence.Context;
global using Axity.Users.Persistence.DAO.Users;
global using Axity.Users.Persistence.DAO.Users.Impl;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
