// <auto-generated/>
global using Axity.Users.Common.DTOs.Requests.Users;
global using Axity.Users.Common.DTOs.Responses.Users;
global using Axity.Users.Facade.Users;
global using Axity.Users.Facade.Users.Impl;
global using Axity.Users.Services.Users;
global using Microsoft.Extensions.DependencyInjection;